### ISSUE TITLE
Reupload ZDResearch - Reverse Engineering

### ISSUE THREAD

**Issue by peipey11** [yialexlee/CTF-Cyber-Security-Source#1]
Hey the Mega link :https://mega.nz/folder/UPglGYbQ#Hhs0lwMZcKkP7CS_fdLJ5w is currently down.It would be really Helpful if you could reupload it again.Thank You!

**Comment by yialexlee** [comment]
Sorry, the file is missing. I'm not able to reupload it.

**Comment by Brainhub24** [comment]
**After login search for it here: [@pan.huang1111.cn](https://pan.huang1111.cn/s/v8XwSE?path=%2F)
Pass:revteam.re**

**Comment by yialexlee** [comment]
@Brainhub24 Thanks for sharing
